<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/UsrYatch/Schemas/UsrDriveType/UsrDriveType.cs" Condition="Exists('$(PkgPath)/UsrYatch/Schemas/UsrDriveType/UsrDriveType.cs')" />
		<Compile Include="$(PkgPath)/UsrYatch/Schemas/UsrPassengersCount/UsrPassengersCount.cs" Condition="Exists('$(PkgPath)/UsrYatch/Schemas/UsrPassengersCount/UsrPassengersCount.cs')" />
		<Compile Include="$(PkgPath)/UsrYatch/Schemas/UsrTrafficLight/UsrTrafficLight.cs" Condition="Exists('$(PkgPath)/UsrYatch/Schemas/UsrTrafficLight/UsrTrafficLight.cs')" />
		<Compile Include="$(PkgPath)/UsrYatch/Schemas/UsrYatchs/UsrYatchs.cs" Condition="Exists('$(PkgPath)/UsrYatch/Schemas/UsrYatchs/UsrYatchs.cs')" />
		<Compile Include="$(PkgPath)/UsrYatch/Schemas/UsrYatchStatus/UsrYatchStatus.cs" Condition="Exists('$(PkgPath)/UsrYatch/Schemas/UsrYatchStatus/UsrYatchStatus.cs')" />
	</ItemGroup>
</Project>